import Header from "@/sharedComponents/header/Index";
import "bootstrap/dist/css/bootstrap.css";
import "styles/globals.css";
import { Provider } from "react-redux";
import { wrapper } from "../store";
import Head from "next/head";
import { useEffect, useState } from "react";

const MyApp = ({ Component, pageProps }) => {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  if (Component.getLayOut) {
    return Component.getLayOut(<Component {...pageProps} />);
  }
  return (
    <>
      <Head>
        <title>Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="bg-light">
        <Header />
        <div className="container-fluid">
          <Component {...pageProps} />
        </div>
      </div>
    </>
  );
};

export default wrapper.withRedux(MyApp);

// MyApp.getInitialProps = async (props) => {
//   return {
//     props: {},
//   };
// };
